'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DownloadLink
    Public Property DownloadLinkID As Long
    Public Property OrderDetailId As Integer
    Public Property UserID As Integer
    Public Property Url As String
    Public Property DownloadToken As String
    Public Property ExpiryDate As Date
    Public Property Hits As Integer
    Public Property ExpireAfterDownload As Boolean
    Public Property Downloaded As Boolean

    Public Overridable Property OrderDetail As OrderDetail
    Public Overridable Property User As User

End Class
