'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailTemplate
    Public Property EmailTemplateID As Integer
    Public Property Header As String
    Public Property Body As String
    Public Property Footer As String
    Public Property EmailTemplateTypeId As Integer

    Public Overridable Property EmailTemplateType As EmailTemplateType
    Public Overridable Property SentMails As ICollection(Of SentMail) = New HashSet(Of SentMail)

End Class
