'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailTemplateType
    Public Property EmailTemplateTypeId As Integer
    Public Property Title As String

    Public Overridable Property EmailTemplates As ICollection(Of EmailTemplate) = New HashSet(Of EmailTemplate)

End Class
