'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Menu
    Public Property MenuId As Integer
    Public Property Title As String
    Public Property ParentId As Nullable(Of Integer)
    Public Property UrlType As Nullable(Of Byte)

    Public Overridable Property Childs As ICollection(Of Menu) = New HashSet(Of Menu)
    Public Overridable Property ParentMenu As Menu
    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
