'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NewsSubscription
    Public Property NewsSubscriptionID As Integer
    Public Property EmailAddress As String
    Public Property UserID As Nullable(Of Integer)

    Public Overridable Property User As User

End Class
