'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderDetail
    Public Property OrderDetailId As Integer
    Public Property OrderID As Integer
    Public Property ProductId As Integer
    Public Property Price As Decimal
    Public Property Quantity As Integer

    Public Overridable Property DownloadLinks As ICollection(Of DownloadLink) = New HashSet(Of DownloadLink)
    Public Overridable Property Order As Order
    Public Overridable Property Product As Product

End Class
