'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property OrderID As Integer
    Public Property Amount As Nullable(Of Integer)
    Public Property TrakingNumber As String
    Public Property IsPaied As Boolean
    Public Property UserID As Integer

    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)
    Public Overridable Property User As User

End Class
