'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductFile
    Public Property ProductFileID As Long
    Public Property ProductID As Integer
    Public Property FilePath As String
    Public Property FileName As String
    Public Property GUID As String
    Public Property Capacity As Long

    Public Overridable Property Product As Product

End Class
