'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductCategory
    Public Property ProductCategoryID As Integer
    Public Property Title As String
    Public Property ParentId As Nullable(Of Integer)

    Public Overridable Property ProductCategories1 As ICollection(Of ProductCategory) = New HashSet(Of ProductCategory)
    Public Overridable Property ProductCategory1 As ProductCategory
    Public Overridable Property UserProductCategoryFavorites As ICollection(Of UserProductCategoryFavorite) = New HashSet(Of UserProductCategoryFavorite)

End Class
