'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductTag
    Public Property ProductTagID As Integer
    Public Property ProductId As Integer
    Public Property TagID As Integer

    Public Overridable Property Product As Product
    Public Overridable Property Tag As Tag

End Class
