'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductId As Integer
    Public Property Name As String
    Public Property Price As Decimal
    Public Property DimentionW As Decimal
    Public Property DimentionD As Decimal
    Public Property DimentionH As Decimal
    Public Property DimentionS As Decimal
    Public Property ProductCategoryId As Integer
    Public Property Description As String

    Public Overridable Property Menu As Menu
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)
    Public Overridable Property ProductFiles As ICollection(Of ProductFile) = New HashSet(Of ProductFile)
    Public Overridable Property ProductPics As ICollection(Of ProductPic) = New HashSet(Of ProductPic)
    Public Overridable Property ProductTags As ICollection(Of ProductTag) = New HashSet(Of ProductTag)
    Public Overridable Property UserFavorites As ICollection(Of UserFavorite) = New HashSet(Of UserFavorite)

End Class
