'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SentMail
    Public Property SentMailID As Integer
    Public Property EmailTemplateID As Integer
    Public Property SentBody As String
    Public Property UserID As Integer

    Public Overridable Property EmailTemplate As EmailTemplate
    Public Overridable Property User As User

End Class
