'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tag
    Public Property TagID As Integer
    Public Property Title As String

    Public Overridable Property ProductTags As ICollection(Of ProductTag) = New HashSet(Of ProductTag)

End Class
