'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserProductCategoryFavorite
    Public Property UserProductCategoryFavoriteID As Integer
    Public Property ProductCategoryID As Integer
    Public Property UserId As Integer

    Public Overridable Property ProductCategory As ProductCategory
    Public Overridable Property User As User

End Class
